require "test_helper"

class ListCategoriesTest < ActionDispatch::IntegrationTest
  def setup
    @category = Category.create(name: "Sports")
    @category2 = Category.create(name: "Travel")
  end

  test "Should show categories listing" do
    # first we need to get to the page/view
    get '/categories'

    # this is getting a link that matches the link generated by category_path(@category)
    # however we dont want to show up as teh href we want the text to be the name so we add ", text: @category.name"
    assert_select "a[href=?]", category_path(@category), text: @category.name
    assert_select "a[href=?]", category_path(@category2), text: @category2.name
  end
end
